name: Manual workflow
on:
  workflow_dispatch:
jobs:
  greet:
    runs-on: self-hosted
    steps:
    - name: deploy
      uses: techlanders-jai/hello-world-javascript-action2@main
      with:
        who-to-greet: "Mona The Octocat"
    - name: Get the time
      run: echo "deploying to environment at ${{ steps.hello.outputs.time }}"
